# Generated by Django 4.0.6 on 2022-09-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_followerscount_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_profileImg',
            field=models.ImageField(default='blank-profile-picture.webp', upload_to=''),
        ),
    ]
