# Generated by Django 4.0.6 on 2022-09-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_user_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profileImg',
        ),
    ]
